name: Auto Commit

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make Changes
        run: |
          echo "Auto Commit: $(date)" >> log.txt
          git diff --quiet && exit 0  # Prevent commit if no changes

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git pull origin main || true  # Prevent failures if pull is not needed
          git add .
          git commit -m "Auto commit $(date)" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
